name: actions

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: ./mvnw install
  dragonchu-blog-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Login to Aliyun Container Registry (ACR)
      uses: aliyun/acr-login@v1
      with:
        login-server: https://registry.cn-hangzhou.aliyuncs.com
        region-id: cn-hangzhou
        username: "${{ secrets.ACR_USERNAME }}"
        password: "${{ secrets.ACR_PASSWORD }}"
    - name: pwd
      run: pwd
    - name: ls
      run: cd ../ && ls
    - name: Build Docker Image
      run: bash docker/build.sh
    - name: Push Docker Image
      run: bash docker/push.sh
