name: actions

on: [push, pull_request]

jobs:
  dragonchu-blog-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Aliyun Container Registry (ACR)
      uses: aliyun/acr-login@v1
      with:
        login-server: https://registry.cn-hangzhou.aliyuncs.com
        region-id: cn-hangzhou
        username: "${{ secrets.ACR_USERNAME }}"
        password: "${{ secrets.ACR_PASSWORD }}"
    - name: Build Docker Image
      run: bash docker/build.sh
    - name: Push Docker Image
      run: bash docker/push.sh
